# tinygrad relies on metal support
c_stdlib_version:   # [osx]
  - 15.5            # [osx]
MACOSX_SDK_VERSION: # [osx]
  - 15.5            # [osx]

github_actions_labels:  # [osx and arm64]
  - depot-macos-15      # [osx and arm64]
