context:
  version: "0.14.0"
  build_number: 0
  # see github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
  proc_type: ${{ "cuda" ~ cuda_compiler_version | version_to_buildstring if cuda_compiler_version != "None" else "cpu" }}
  # we don't want to leave random substitution left-overs; use naming of CUDA 12 for CPU variant
  cuda_pseudo_so: ${{ (cuda_compiler_version|default("12") | split('.'))[0] ~ "0" }}

recipe:
  name: tinygrad
  version: ${{ version }}

source:
  - url: https://github.com/tinygrad/tinygrad/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 6567baffbed558cb398b2d1cbff3bb128ebed491478693d32ac27cddd23dad2b
    patches:
      # search CONDA_PREFIX first, esp. for llvmdev/clangdev/CUDA
      - patches/0001-look-for-libraries-in-PREFIX-first.patch
      # see more clearly what's happening in mnist test
      - patches/0002-update-accuracy-for-every-step-in-beautiful_mnist.py.patch
      # use CONDA_BUILD_SYSROOT instead of whatever's lying around in image
      - patches/0003-use-our-standard-macos-sdk.patch
      # ensure we find vendored applegpu
      - patches/0004-make-apple-disassembler-runnable-when-installed.patch
      - if: osx and x86_64
        then:
          # disable metal on osx
          - patches/0005-default-to-CPU-as-device-on-osx-64-remove-metal.patch
      - if: osx and arm64
        then:
          # cannot disassemble metal when using vanilla clang; see
          # https://github.com/tinygrad/tinygrad/issues/14005
          - patches/0006-skip-metal-disassembly-for-vanilla-clang.patch
      # revert https://github.com/tinygrad/tinygrad/pull/14086 (until we have ggml)
      - patches/0007-Revert-don-t-skip-gguf-test-if-ggml-is-not-installed.patch
      - patches/0008-skip-test-for-models-that-are-not-available-anymore.patch
      # nvcc complains if clang is too new, even with v20, which upstream uses
      - patches/0009-allow-newer-clang-with-nvcc.patch
      - patches/0010-avoid-redundant-definitions-of-INFINITY-NAN.patch
      - if: osx and arm64
        then:
          - patches/0011-force-metal-version.patch
  - if: osx and arm64
    then:
      - target_directory: tinygrad/extra/disassemblers/applegpu
        git: https://github.com/dougallj/applegpu
        rev: "797862eea0cee1f1eba74be3d0d02be4b3d2bd0d"

build:
  number: ${{ build_number }}
  string: ${{ proc_type }}_py${{ python | version_to_buildstring }}_h${{ hash }}_${{ build_number }}
  skip:
    - match(python, "<3.11")

outputs:
  - package:
      name: tinygrad
    build:
      script:
        # do this unconditionally to not leave around random substitution left-overs
        - 'sed -i "s/@CUDA_VERSION@/${{ cuda_pseudo_so }}/" tinygrad/runtime/autogen/__init__.py'
        - 'sed -i "s/@CUDA_VERSION@/${{ cuda_pseudo_so }}/" tinygrad/runtime/autogen/nvjitlink.py'
        - 'sed -i "s/@CUDA_VERSION@/${{ cuda_pseudo_so }}/" tinygrad/runtime/autogen/nvrtc.py'
        - python -m pip install . -vv
        - if: osx and arm64
          then:
            - mkdir -p $SP_DIR/tinygrad/extra/disassemblers/applegpu
            - cp -R ./tinygrad/extra/disassemblers/applegpu/* $SP_DIR/tinygrad/extra/disassemblers/applegpu
            - cd $SP_DIR/tinygrad/extra/disassemblers/applegpu/compiler_explorer_tools
            - make
    requirements:
      build:
        - if: build_platform != host_platform
          then:
            - python
            - cross-python_${{ host_platform }}
        # this is just here so smithy creates separate jobs for the CUDA variants
        - if: cuda_compiler_version != "None"
          then:
            - ${{ stdlib("c") }}
            - ${{ compiler("cxx") }}
            - ${{ compiler("cuda") }}
        - if: osx and arm64
          then:
            - make
            # for bare clang/clang++ symlinks, see
            # https://github.com/dougallj/applegpu/blob/main/compiler_explorer_tools/Makefile
            - clang
            - clangxx
        - if: unix
          then: sed
          else: m2-sed
      host:
        - python
        - pip
        - setuptools
      run:
        - python
        - capstone
        - llvmdev
        - clangxx_${{ host_platform }}
        # tinygrad wants headers from `include/clang-c`; also ensure `bin/clang` symlink is present
        - clangdev
        # avoid solver choosing ancient clang versions
        - clang >18
        - if: cuda_compiler_version != "None"
          then:
            - __cuda
            - cuda-nvcc_${{ host_platform }}
            - cuda-nvrtc-dev
            - libnvjitlink-dev
            - if: x86_64
              then:
                - cuda-opencl-dev
            - if: linux
              then:
                - triton
      run_constraints:
        - if: linux
          then:
            # avoid wrong compiler activation that interferes with clang_<target>
            - gcc_linux-64 <0.0a0
            - gxx_linux-64 <0.0a0
            - gcc_linux-aarch64 <0.0a0
            - gxx_linux-aarch64 <0.0a0
        - if: win
          then:
            # avoid pulling in old MSVC activation
            - vs2019_win-64 <0.0a0
    tests:
      - python:
          imports:
            - tinygrad
            - tinygrad.runtime.autogen.libclang
            - tinygrad.runtime.autogen.llvm
          pip_check: true
      - script:
          # not covered by bare import test, because these are all members with try/except fallbacks
          - python -c "from tinygrad.runtime.autogen.libclang import clang_getFile"
          - python -c "from tinygrad.runtime.autogen.llvm import LLVMParseBitcode"
          - if: linux
            then:
              - python -c "from tinygrad.runtime.autogen.libc import syscall"
          - if: cuda_compiler_version != "None"
            then:
              - python -c "from tinygrad.runtime.autogen.nvrtc import nvrtcGetPTXSize"
              - python -c "from tinygrad.runtime.autogen.nvjitlink import nvJitLinkAddFile"
              - if: x86_64
                then:
                  - python -c "from tinygrad.runtime.autogen.opencl import clGetDeviceInfo"
      # integration-test in addition to test suite below
      - files:
          source:
            - examples/beautiful_mnist.py
        script:
          # reduce number of steps; we just need to show that it's functional
          # however, accuracy should at least trend in the right direction
          # we remove $PYTHON because it makes Tensor.device autoselection choke
          - if: unix
            then:
              - export STEPS=25
              - export TARGET_EVAL_ACC_PCT=90
              - unset PYTHON
            else:
              - set "STEPS=25"
              - set "TARGET_EVAL_ACC_PCT=90"
              - set "PYTHON="
          - if: match(cuda_compiler_version, "!=13.0")
            then:
              - python ./examples/beautiful_mnist.py
          # run again with high DEBUG value; exercises different paths, e.g. needs capstone
          - if: unix
            then:
              - export STEPS=1
              - export DEBUG=10
              - unset TARGET_EVAL_ACC_PCT
            else:
              - set "STEPS=1"
              - set "DEBUG=10"
              - set "TARGET_EVAL_ACC_PCT="
          - if: not aarch64 and match(cuda_compiler_version, "!=13.0")
            then:
              # suppress enormously noisy output; re-enable if things actually fail
              - python ./examples/beautiful_mnist.py > /dev/null

  - package:
      name: tinygrad-tests
    build:
      skip:
        # redundant but: https://github.com/prefix-dev/rattler-build/issues/2110
        - match(python, "<3.11")
        # onnxruntime not available in this platform/python combo
        - osx and x86_64 and match(python, ">=3.14")
      # splitting off what conda packages under etc/conda/test-files when using test.files.source
      script:
        - if: unix
          # silly: https://github.com/prefix-dev/rattler-build/pull/1367
          then: true
          else:
            - echo "nothing"

    requirements:
      run:
        - ${{ pin_subpackage('tinygrad', exact=True) }}
    tests:
      - requirements:
          run:
            # minimal
            - pytest
            - pytest-xdist
            - hypothesis
            - ml_dtypes
            - numpy
            - pytorch
            - z3-solver
            # optional
            - blobfile
            - boto3
            - bottle
            # https://github.com/conda-forge/staged-recipes/issues/29179
            # - ggml-python
            - if: unix
              then:
                # not available on windows yet
                - jax
            - librosa
            - networkx
            - nibabel
            - onnx2torch
            - onnx
            - onnxruntime
            - openai
            - pandas
            - py-opencv
            - pybind11
            - pycocotools
            - pillow
            # Makes test/unit/test_disk_tensor.py::TestSafetensors::test_load_supported_types fail
            - safetensors <0.8.0dev0
            - sentencepiece
            - tabulate
            - tiktoken
            - tqdm
            - transformers
        files:
          source:
            - examples/
            - extra/
            - test/
        script:
          interpreter: python
          content:
            - 'import pytest'
            - 'import sys'
            - 'import os'
            # $PYTHON makes Tensor device autoselection choke
            - 'os.environ.pop("PYTHON", None)'
            - 'os.environ.setdefault("ONEDNN_VERBOSE", "all")'
            - 'tests_to_skip = "_not_a_real_test"'
            - if: linux
              then:
                # fails `assert Device.DEFAULT in failed_platforms`
                - 'tests_to_skip += " or (TestLinearizerFailures and test_failure_27)"'
                # Causes `Fatal Python error: Bus error` + segfault
                - 'tests_to_skip += " or testCopySHMtoDefault"'
                # RuntimeError: Attempting to relocate against an undefined symbol 'fmaxf'
                - 'tests_to_skip += " or test_backward_sum_acc_dtype"'
                # cannot load onnx model from some temporary location
                - 'tests_to_skip += " or (TestQuantizeOnnxCPU and test_quant_128)"'
                # No such file or directory: '/tmp/tmpqhndyk1l.so'
                - 'tests_to_skip += " or test_bitfield_interop or test_packed_struct_interop"'
                # mismatch in expected number of relocations
                - 'tests_to_skip += " or test_load_clang_jit_strtab"'
                # flaky, server seems to hang or run into a race condition of sorts
                - 'tests_to_skip += " or test_getotherprocess or test_putotherprocess"'
                - if: cuda_compiler_version != "None"
                  then:
                # GC clean-up error
                    - 'tests_to_skip += " or test_assign_refcount"'
                # RuntimeError: Attribute list does not match Module context!
                    - 'tests_to_skip += " or test_bf16_disk_write_read"'
                # expects zero memory use for `.schedule()`
                    - 'tests_to_skip += " or test_schedule_mem_used"'
                # slightly higher memory use than anticipated
                    - 'tests_to_skip += " or test_unet_resblock"'
                # somehow fails to stat (or create?!) a temporary file
                    - 'tests_to_skip += " or test_save_all_dtypes"'
                    - 'tests_to_skip += " or (TestDiskTensorMovement and test_slice)"'
            - if: linux and aarch64
              then:
                # expects array([0]), gets array([255])
                - 'tests_to_skip += " or test_float_cast_to_unsigned_underflow"'
                - if: match(python, ">=3.13")
                  then:
                # These fail with: could not create a primitive descriptor for the ... primitive.
                # Run workload with environment variable ONEDNN_VERBOSE=all to get additional diagnostic information.
                    - 'tests_to_skip += " or test_gemm_fp16 or test_conv2d_fused_half or test_conv2d_half"'
            - if: osx or (linux and cuda_compiler_version != "None")
              then:
                # beam-related stuff seems to hang on metal, OOM/crash with CUDA
                - 'tests_to_skip += " or TestBEAM or test_beam"'
            - if: osx
              then:
                # another apparent hang
                - 'tests_to_skip += " or test_getotherprocess"'
                # forking too early
                - 'tests_to_skip += " or test_putotherprocess"'
                # running into weakly-referenced object no longer exists
                - 'tests_to_skip += " or TestGC or test_gc"'
                - if: arm64
                  then:
                    - 'tests_to_skip += " or (TestOpsUint8 and test_cast)"'
            - if: osx and x86_64
              then:
                # signed int32 overflow
                - 'tests_to_skip += " or test_float_midcast_int32"'
                # tinygrad.codegen.kernel.KernelOptError: must have tensor cores or TC=2
                - 'tests_to_skip += " or test_unmerged_ifs"'
                # RuntimeError: The MPS backend is supported on MacOS 14.0+
                - 'tests_to_skip += " or test_torch_interop"'
                # element mismatch in array
                - 'tests_to_skip += " or test_conv2d_fused"'
                # flaky hypothesis test
                - 'tests_to_skip += " or test_float_cast_to_unsigned"'
                # less operations on CPU than expected on metal, apparently
                - 'tests_to_skip += " or test_jit_split_simple"'

            # test suite in emulation on aarch is super slow, skip it there
            - if: unix and build_platform == host_platform
              then:
                - 'sys.exit(pytest.main(["-v", "test/", "-k", f"not ({tests_to_skip})", "--durations=50", "--maxfail=20"]))'

about:
  homepage: https://github.com/tinygrad/tinygrad
  summary: 'You like pytorch? You like micrograd? You love tinygrad! ❤️'
  description: |
    This may not be the best deep learning framework, but it is a deep learning framework.

    Due to its extreme simplicity, it aims to be the easiest framework to add new accelerators to,
    with support for both inference and training. If XLA is CISC, tinygrad is RISC.
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - applegpu_LICENSE
  documentation: https://docs.tinygrad.org/
  repository: https://github.com/tinygrad/tinygrad

extra:
  recipe-maintainers:
    - h-vetinari
  feedstock-name: tinygrad
